exclude = [
  "@ref",
  "@cite",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://TulipaEnergy.github.io/ElectricityNetworkReduction.jl/stable$",
  "https://blog.esciencecenter.nl/the-utopic-git-history-d44b81c09593",
  "zenodo.org/badge/DOI/FIXME$",
  "https://tulipaenergy.github.io/ElectricityNetworkReduction.jl/stable",
  "https://tulipaenergy.github.io/ElectricityNetworkReduction.jl/dev",
]

exclude_path = [
  "docs/build"
]
